# Generated by Django 3.2.6 on 2021-08-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_keep', '0003_remove_note_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='todos',
            field=models.ManyToManyField(blank=True, null=True, related_name='todos', to='google_keep.Checkbox'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='google_keep.keepuser'),
        ),
    ]
