# Generated by Django 3.2.6 on 2021-08-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_keep', '0004_auto_20210806_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keepuser',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='keepuser',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
