# Generated by Django 3.2.6 on 2021-08-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_keep', '0006_auto_20210820_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keepuser',
            options={'verbose_name': 'جا کاربری', 'verbose_name_plural': 'جا کاربری ها'},
        ),
        migrations.AddField(
            model_name='keepuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است؟'),
            preserve_default=False,
        ),
    ]
