# Generated by Django 3.2.6 on 2021-08-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_keep', '0007_auto_20210820_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است؟'),
        ),
    ]
